import { Providers } from '../store/Providers'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
      {/* EL PROVIDER LO HAGO ACÁ EN EL COMPONENTE PROVIDERS, PORQUE SI O SI TIENE QUE SER 'USE CLIENT', Y SI ES 'USE CLIENT' NO PUEDO PONERLE METADATA. */}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}

